# Generated by Django 4.2.4 on 2023-08-28 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryData', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boxes',
            name='updated_on',
            field=models.DateTimeField(null=True),
        ),
    ]
